import type { Metadata } from "next";
 import "./globals.css";
import { ThemeProvider } from "@/components/themes/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Toaster } from "@/components/ui/toaster";
import { DesignerContextProvider } from "@/context/designer-context";
import NextTopLoader from 'nextjs-toploader';

 

export const metadata: Metadata = {
  title: "BuildaForm",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
       <head>
  <link rel="icon" href="/buildaform-1.png" type="image/svg+xml" />
        </head>

      <body
        className={` font-mono antialiased custom-scrollbar `}
      >
        <DesignerContextProvider>

        <ClerkProvider
      appearance={{
        baseTheme:dark,
        variables:{colorPrimary:'#3371FF',
          fontSize:'16px'
        }
      }}
      >
              <ThemeProvider
                      attribute="class"
                      defaultTheme="dark"
                      enableSystem
                      disableTransitionOnChange
                    >
        {children}
        <Toaster />
        </ThemeProvider>
        </ClerkProvider>
      </DesignerContextProvider>
      </body>
    </html>
  );
}
